version: '2'

services:
  app:
    image: 'backend'
    build: .
    ports:
      - 8000:8000
    container_name: backendprueba
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_tingeso
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
          
  db:
    image: 'postgrest2'
    container_name: postgrestprueba
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_tingeso
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  